### ISSUE TITLE
Remove @internal annotation from PHPMock::getMockBuilder

### ISSUE THREAD

**Issue by sc0rp10** [php-mock/php-mock-phpunit#13]
In my IDE (PhpStorm) this annotation mark method call as a problem.
![](https://cdn.weblab.pro/x3kb5.png)
Maybe is there reason for remove this for clear and helpful IDE messages?

**Comment by malkusch** [comment]
I use the [`@internal` annotation](https://phpdoc.org/docs/latest/references/phpdoc/tags/internal.html) to mark

> that the associated Structural Elements are used purely for the internal workings of this piece of software.

In particular to avoid apearing such internal details in the [API documentation](http://php-mock.github.io/php-mock-phpunit/api/class-phpmock.phpunit.PHPMock.html).

I actually don't need those abstract methods in the trait. I have them there for convenience, so that the code makes sense while calling those methods from the expected PHPUnit API.

But for you as a PHPUnit user they are part of the public API of PHPUnit. Actually I don't know what should be a correct behaviour for this case. I don't think it's well defined in PHPDoc and last time I checked, this PSR soap was about to implode or at least the PHPDoc-PSR died. Ok, before I make any action on that, I need some authoritative information about the correct behaviour. I'll try to get that from https://github.com/phpDocumentor/phpDocumentor2.

**Comment by emirb** [comment]
@malkusch Can you fully remove those abstract methods in the trait, as you said you don't need them actually? They add no value and just pollute inspections in PhpStorm.

**Comment by webimpress** [comment]
@emirb Please see #27, methods from trait are there removed.

**Comment by emirb** [comment]
Thanks @webimpress!
