### ISSUE TITLE
Support PHPUnit 10

### ISSUE THREAD

**Issue by herndlm** [php-mock/php-mock-phpunit#55]
fyi I wanted to open a PR, but most likely to properly test it also prophecy (dev dep from this package) needs to get PHPUnit 10 support first. Looks like they're already working on it via https://github.com/phpspec/prophecy/pull/585

**Comment by michalbundyra** [comment]
@herndlm thanks, I've seen it already, was thinking about dropping prophecy here, there are going to be more issues in general here, so I am even tempted to support only PHPUnit 10 (or 9 and 10) in next minor release to clean up this package a bit. It's horrible mess atm.

**Comment by michalbundyra** [comment]
@herndlm instead of waiting for prophecy to get PHPUnit 10 support I've tried with mockery as the second mocking library in our tests - and it seems to be successful. PHPUnit 10 support has been provided in PR #56 and just released in [2.7.0](https://github.com/php-mock/php-mock-phpunit/releases/tag/2.7.0).

Any feedback appreciated!
