### ISSUE TITLE
Incompatible with PHPUnit >= 10.3

### ISSUE THREAD

**Issue by mac89** [php-mock/php-mock-phpunit#61]
Caused by making the `$properties` property read only: https://github.com/sebastianbergmann/phpunit/commit/eb2d7611558b4587c37eb7f15549fb06ab62f9cb

**Comment by herndlm** [comment]
I was looking into this a bit and found out the following so far
- reflection cannot be used to modify readonly properties -> https://wiki.php.net/rfc/readonly_properties_v2#reflection
- simply creating a new instance of `Invocation` can also not be done because it does not have a getter for its private prop `returnType` which is needed for construction

Since the whole modification of default params in Invocation is already a hack (Invocation is internal, private `parameters` are modified via closure binding) we could use reflection to only access `returnType` and then "cleanly" create a new instance of `Invocation` maybe?

E.g. I tried the following (only in the one place that broke a test for us!) and it seems to work
```php
private function removeDefaultArguments(Invocation $invocation, string $class)
    {
        $parameters = $invocation->parameters();
        MockFunctionGenerator::removeDefaultArguments($parameters);

        $returnTypePropertyReflection = new \ReflectionProperty(Invocation::class, 'returnType');
        $returnTypePropertyReflection->setAccessible(true);

        $invocation = new Invocation(   
            $invocation->className(),
            $invocation->methodName(),
            $parameters,
            $returnTypePropertyReflection->getValue($invocation),
            $invocation->object()
        );
    }
```

**Comment by michalbundyra** [comment]
@herndlm I was looking into it as well, and I have no solution yet. I am worried we might not have one, or we would need to came up with something else. Yes, this library hacks PHPUnits, and it's already so complex to support all PHPUnit versions. 

Thanks for investigation, I'll try to dig a bit more once I have a bit more time. Thanks again

**Comment by herndlm** [comment]
oh, right, and in my proposed fix I missed that the passed $invocation is not overwritten / returned, so It's not doing anything 🤦‍♂️

**Comment by MekkiLakhdher** [comment]
I am facing the same issue : 
```
Error: Cannot modify readonly property PHPUnit\Framework\MockObject\Invocation::$parameters
...\php-mock\php-mock-phpunit\classes\DefaultArgumentRemoverReturnTypes100.php:76
```
The solution that worked for me is simply using `\PHPUnit\Framework\MockObject\Invocation::parameters` method which is the `getter` of the `readonly $parameters` variable.

Here are the necessary changes :

`/php-mock/php-mock-phpunit/classes/DefaultArgumentRemoverReturnTypes100.php:41`
**-** `MockFunctionGenerator::removeDefaultArguments($invocation->parameters);`
**+** `MockFunctionGenerator::removeDefaultArguments($invocation->parameters());`

And

`/php-mock/php-mock-phpunit/classes/DefaultArgumentRemoverReturnTypes100.php:76`
**-** `MockFunctionGenerator::removeDefaultArguments($this->parameters);`
**+** `MockFunctionGenerator::removeDefaultArguments($this->parameters());`

**Comment by michalbundyra** [comment]
@MekkiLakhdher it does not seem to be working - see: https://github.com/php-mock/php-mock-phpunit/pull/62
(commit: https://github.com/php-mock/php-mock-phpunit/pull/62/commits/1dfcf667231ceaf4178f10a6f383b09a8572f85d)

**Comment by herndlm** [comment]
nice, thx @marcoscoelho. I can finally merge this one :D

<img width="990" alt="image" src="https://github.com/php-mock/php-mock-phpunit/assets/5738896/2ad15668-3484-4718-a327-d6d26b03ac21">
