### ISSUE TITLE
[QUESTION] - Deprecated Methods in phpunit 11

### ISSUE THREAD

**Issue by ciltocruz** [php-mock/php-mock-phpunit#70]
Hello. After upgrading to PhpUnit 11, it reports some deprecated methods used by php-mock. Is there any plan to avoid using these deprecated methods which will stop working in phpunit 12?

![image](https://github.com/php-mock/php-mock/assets/19903919/390232a8-f8d8-4f77-8665-b40b29a94115)

Thank you.

**Comment by michalbundyra** [comment]
Hi @ciltocruz !

(I have transferred the issue from php-mock to php-mock-phpunit.)

It was noted also here: https://github.com/php-mock/php-mock-phpunit/pull/67#issuecomment-1937702275

I was checking if there is something I can do quickly, but I cannot see easy solution, and we would need a new version of https://github.com/php-mock/php-mock-integration to get it working without deprecations.

The problem is that we do not really know yet what PHPUnit 12 is going to bring, and we might have more issues when it lands.
For now I am not planning to work on removing these deprecations, but if there is someone who wants to provide the fix I would be more than happy to review and release. Hope it makes sense.

Thanks!

**Comment by ciltocruz** [comment]
Perfect. Thank you for transferring it here. We'll wait for that version 12 to see what needs to be done. I close this issue to avoid noise.
